export interface CardStyleConfig {
  id: string;
  name: string;
  badge: string;
  description: string;
  bgGradient: string;
  previewImg: string;
  isLocked: boolean;
  isAvailable: boolean;
  stagesCount: number;
  route: string;
}

export const CARD_STYLES: CardStyleConfig[] = [
  {
    id: 'original-signature',
    name: 'Original Signature',
    badge: 'Възрастни / Универсален',
    description: 'Луксозен минимализъм, Soft Silk, дълбоки тонове, 3D восъчен печат и златно фолио за изтъркване.',
    bgGradient: 'from-[#FAF6EE] to-[#EAE2D6]',
    previewImg: '/images/cards/card-1.png',
    isLocked: false,
    isAvailable: true,
    stagesCount: 6,
    route: '/create/birthday/basic',
  },
  {
    id: 'detective-mystery',
    name: 'Detective Mystery',
    badge: 'Любители на пъзели',
    description: 'Ноар атмосфера, папки TOP SECRET и червени печати с търсене с виртуална лупа и дешифриране.',
    bgGradient: 'from-[#2C2622] to-[#141210]',
    previewImg: '/images/cards/card-2.png',
    isLocked: false,
    isAvailable: true,
    stagesCount: 6,
    route: '/create/birthday/detective-mystery',
  },
  {
    id: 'escape-room',
    name: 'Escape Room',
    badge: 'Стаята на загадките',
    description: 'Интерактивно приключение с кодове, таймери и логически стъпки.',
    bgGradient: 'from-[#3A3532] to-[#1A1816]',
    previewImg: '/images/cards/card-1.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 6,
    route: '/create/birthday/escape-room',
  },
  {
    id: 'editorial-magazine',
    name: 'Editorial Magazine',
    badge: 'Мода и стил - Дами',
    description: 'Корица на списание с елегантна типография, разлистване (Swipe) и блиц интервю.',
    bgGradient: 'from-[#FFF0F5] to-[#F5E6EC]',
    previewImg: '/images/cards/card-3.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 5,
    route: '/create/birthday/editorial-magazine',
  },
  {
    id: 'retro-arcade',
    name: 'Retro Arcade',
    badge: 'Геймъри',
    description: '8-битов пиксел арт, аркадни машини, Boss battle с помпане на бутон и отключване на съкровище.',
    bgGradient: 'from-[#1A1A2E] to-[#16213E]',
    previewImg: '/images/cards/card-4.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 6,
    route: '/create/birthday/retro-arcade',
  },
  {
    id: 'boarding-pass',
    name: 'Boarding Pass',
    badge: 'Пътешественици',
    description: 'Летищна естетика, билети, глобуси, печати, сканиране на штрихкод и търкащ се глобус.',
    bgGradient: 'from-[#F0F8FF] to-[#E0F0FF]',
    previewImg: '/images/cards/card-2.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 5,
    route: '/create/birthday/boarding-pass',
  },
  {
    id: 'kids-fairytale',
    name: 'Kids Fairytale',
    badge: 'Деца 3-6 г.',
    description: '3D Disney Pixar стил, палитра от меки и луксозни детски тонове с помощ за анимиран герой и пукане на балони.',
    bgGradient: 'from-[#FFF8DC] to-[#FFF0F5]',
    previewImg: '/images/cards/card-2.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 5,
    route: '/create/birthday/kids-fairytale',
  },
  {
    id: 'secret-diary',
    name: 'Secret Diary',
    badge: 'Момичета 7-12 г.',
    description: 'Тайни дневници, пастелни цветове, стикери, photo scrapbook викторина и Fashion vibe creator.',
    bgGradient: 'from-[#FFE4E1] to-[#FFF0F5]',
    previewImg: '/images/cards/card-3.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 5,
    route: '/create/birthday/secret-diary',
  },
  {
    id: 'agent-heist',
    name: 'Agent Heist',
    badge: 'Момчета 7-12 г.',
    description: 'Шпионска лаборатория, Minecraft/Roblox вайб, лазерен лабиринт и хакване на сейф.',
    bgGradient: 'from-[#111827] to-[#1F2937]',
    previewImg: '/images/cards/card-4.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 6,
    route: '/create/birthday/agent-heist',
  },
  {
    id: 'aesthetic-dump',
    name: 'Aesthetic Dump',
    badge: 'Тийнейджъри - Момичета',
    description: 'TikTok/Reels скрол, Y2K винтидж филтри, Moodboard с вертикален скрол със скрити тагове и Which Vibe куиз.',
    bgGradient: 'from-[#F3E8FF] to-[#FCE7F3]',
    previewImg: '/images/cards/card-3.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 5,
    route: '/create/birthday/aesthetic-dump',
  },
  {
    id: 'level-up-cyber',
    name: 'Level Up Cyber',
    badge: 'Тийнейджъри - Момчета',
    description: 'Cyberpunk, Discord/Twitch интерфейс, Dark mode, Speedrun таймер със загадки и System Hack.',
    bgGradient: 'from-[#0F172A] to-[#1E1B4B]',
    previewImg: '/images/cards/card-4.png',
    isLocked: true,
    isAvailable: false,
    stagesCount: 6,
    route: '/create/birthday/level-up-cyber',
  },
];

